version: "3"

services:

  frontend:

    container_name: frontend

    build:
      context: ./frontend

    ports:
      - "5173:5173"

    networks:
      - fullstack

    depends_on:
      - backend

  
  backend:

    container_name: backend

    build:
      context: ./backend

    ports:
      - "8000:8000"

    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

    networks:
      - fullstack

    depends_on:
      db:
        condition: service_healthy


  db:

    container_name: postgres_db

    image: postgres:15

    restart: always

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 30s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - fullstack

volumes:
  postgres_data:

networks:
  fullstack:
